#!/usr/bin/env -S go run github.com/rliebz/tusk@latest --file tusk.yaml boot -c
---
#cloud-config
# users:
# - name: "bar"
#   passwd: "foo"
#   groups: "users"
#   ssh_authorized_keys:
#   - faaapploo
# ssh_authorized_keys:
#   - asdd
runcmd:
- neofetch
- echo "{{.Values.node.hostname}}"
# hostname: "bar"
# write_files:
# - encoding: b64
#   content: CiMgVGhpcyBmaWxlIGNvbnRyb2xzIHRoZSBzdGF0ZSBvZiBTRUxpbnV4
#   path: /foo/bar
#   permissions: "0644"
#   owner: "bar"